### PR TITLE
Upgrade to tokio 1.4

### PR DESCRIPTION
**Pull request by paulfariello**
Try to upgrade to tokio 1.4

### CODE REVIEW

**Comment by harporoeder** [comment]
Hi @paulfariello thanks for the PR! Looks pretty good from a glance. I'll go over this in the very near future, and get a new release up. I am a bit busy today.

**Comment by paulfariello** [comment]
Rebased on master

**Comment by harporoeder** [comment]
Awesome. Thanks for all the work you put into this PR! I ran the integration tests (which I do run currently run in CI) and everything still passes. I'll merge this and get a new release up now. I'll will bump to `0.12.0` to be on the safe side for consumers.

**Comment by paulfariello** [comment]
Thanks for the original work and thanks for reviewing and merging this MR this quick.

**Pull request merged**
